spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 569030786242-d0lqed4e3nsjnudtkvp3g9l478dq62up.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
  datasource:
    url: "jdbc:postgresql://localhost:15432/campsitedemo?currentSchema=public"
    username: campsite
    password: campsite
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 10000       # 10s
      validation-timeout: 5000        # 5s
      max-lifetime: 1800000           # 30min
      leak-detection-threshold: 60000 # 1min
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
  flyway:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

campsite:
  capacity: 30
  timeZone: UTC


springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "documentation.html"
    operationsSorter: method
    filter: false