spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 569030786242-d0lqed4e3nsjnudtkvp3g9l478dq62up.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
  datasource:
    url: "jdbc:postgresql://localhost:15432/campsitedemo?currentSchema=public"
    username: campsite
    password: campsite
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 10000       # 10s
      validation-timeout: 5000        # 5s
      max-lifetime: 1800000           # 30min
      leak-detection-threshold: 60000 # 1min
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 15
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
  flyway:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

campsite:
  capacity: 30
  timeZone: UTC


springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "documentation.html"
    operationsSorter: method
    filter: false